/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-05-03T08:23:41.414Z[GMT]")
@Api(value = "caseIdentifiers", description = "the caseIdentifiers API")
public interface CaseIdentifiersApi {

    @ApiOperation(value = "SEQ-case-check-caseid-availablity: Check caseId availability", nickname = "sEQCaseCheckCaseidAvailablityCheckcaseIdavailability", notes = "If the WC1 client has an ID to use when creating a case, check if it is available for use in World-Check One, or find out if an existing case with that ID already exists.", tags={ "Misc", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "") })
    @RequestMapping(value = "/caseIdentifiers",
        method = RequestMethod.GET)
    ResponseEntity<Void> sEQCaseCheckCaseidAvailablityCheckcaseIdavailability(@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "caseId", required = true) String caseId
,@ApiParam(value = "" ,required=true) @RequestHeader(value="Date", required=true) String date
,@ApiParam(value = "" ,required=true) @RequestHeader(value="org.akash.Authorization", required=true) String authorization
,@ApiParam(value = "",required=true) @PathVariable("gateway-host") String gatewayHost
,@ApiParam(value = "",required=true) @PathVariable("gateway-url") String gatewayUrl
);

}
